services:
  db:
    env_file:
      - .env
    image: mongo
    restart: always
    container_name: jkpg_db
    environment:
      - MONGO_URI=mongodb://localhost:27017/development
    ports:
      - "5551:${MONGO_PORT}"
    volumes:
      - mongo_data_dev:/data/db

volumes:
  mongo_data:
    name: mongo_data_dev
