apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkpg-deployment # name on the app
  namespace: jkpg-city-replica # The namespace you choose
spec:
  replicas: 1
  selector:
    matchLabels:  # Ensure correct "matchLabels" key
      app: jkpg-app # Ensure label matches pod template metadata
  template:
    metadata:
      labels:  # Ensure correct "labels" key
        app: jkpg-app # Ensure label matches selector
    spec:
      containers:
        - name: jkpg-app
          image: localhost:5000/jkpg-app:latest
          
          
              
        #can i do it like this and specifed the port? https://www.freecodecamp.org/news/deploy-docker-image-to-kubernetes/

        # is like an container in k8s
        # kubectl apply -f k8s/deployment.yaml
#kubectl set image deployment/jkpg-city-replica-deployment jkpg-server=localhost:5000/jkpgcity_backend-server:<new-version> 
 #pull the image here only https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy