apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkpg-deployment # name on the app
  namespace: jkpg-city-replica # The namespace you choose
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: jkpg-app 
  template:
    metadata:
      labels:  
        app: jkpg-app 
    spec:
      containers:
        - name: jkpg-app
          image: localhost:5000/jkpg-app:latest
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/jkpg_db"
          imagePullPolicy: Always
          ports:
            - containerPort: 5500
          
          
              
        #can i do it like this and specifed the port? https://www.freecodecamp.org/news/deploy-docker-image-to-kubernetes/

        # is like an container in k8s
        # kubectl apply -f k8s/deployment.yaml
#kubectl set image deployment/jkpg-city-replica-deployment jkpg-server=localhost:5000/jkpgcity_backend-server:<new-version> 
 #pull the image here only https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy