apiVersion: v1
kind: Service
metadata:
  name: jkpg-service #own service name
  namespace: jkpg-city-replica
spec:
  type: LoadBalancer
  selector: 
    app: jkpg-app
  ports:
    - protocol: TCP
      port: 48484
      targetPort: 5500


# service is the netwrok cable
# kubectl apply -f k8s/service.yaml
# kubectl rollout restart deployment/name-deployment -n Namespace
#