apiVersion: v1
kind: Service
metadata:
  name: jkpg-service #own service name
  namespace: jkpg-city-replica
spec:
  selector: 
    app: jkpgcity
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


# service is the netwrok cable
# kubectl apply -f k8s/service.yaml
# kubectl rollout restart deployment/name-deployment -n Namespace
#